* -----------------------------------------------------
* XLS2GMS Version 2.8, January 2005 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     11.0
* Workbook:    C:\Program Files\GAMS22.0\wtoolslib\yield.xls
* Sheet:       data
* Range:       $B$2:$J$23
* -----------------------------------------------------
                  1974  1975  1976  1977  1978  1979 
                                                     
sheep   .    meat 10.6  11.42 10.6  9.38  8.97  6.93 
sheep   .    milk 23.7  24.1  24.2  24.2  24    23.9 
sheep   .    wool 1.3   1.3   1.3   1.3   1.3   1.3  
sheep   .    hide 0.5   0.6   0.6   0.5   0.6   0.4  
goat    .    meat 6.39  7.31  8.68  7.31  6.39  6.85 
goat    .    milk 37.7  38.1  38.2  38.2  38.3  37.8 
goat    .    wool 0.6   0.6   0.6   0.6   0.6   0.6  
goat    .    hide 0.2   0.3   0.3   0.3   0.2   0.3  
angora  .    meat 1.77  1.77  2.66  2.21  1.77  1.77 
angora  .    milk 14.9  15.2  14.8  15.2  14.8  15   
angora  .    wool 1.6   1.6   1.6   1.6   1.6   1.4  
angora  .    hide 0.1   0.1   0.1   0.1   0.1   0.1  
cattle  .    meat 24.59 25.12 21.42 23    18.25 25.12
cattle  .    milk 210   208.1 219.8 213.8 214.8 217.5
cattle  .    hide 3.3   3.4   2.9   3     2.6   3.3  
buffalo .    meat 43.73 45.42 40.61 37.21 32.2  32.68
buffalo .    milk 267.1 269.2 263.8 219.6 275.5 285.1
buffalo .    hide 4.1   3.4   3     2.4   2.5   2.6  
poultry .    meat 2.24  2.24  2.24  2.24  2.24  2.24 
poultry .    egg  62.4  62.2  64.2  78.3  76.4  73.3 
* -----------------------------------------------------
